# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/templates/authors.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_dialog(object):
    def setupUi(self, filter_dialog):
        filter_dialog.setObjectName("filter_dialog")
        filter_dialog.resize(317, 321)
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.undo_button = QtWidgets.QPushButton(filter_dialog)
        self.undo_button.setObjectName("undo_button")
        self.gridLayout.addWidget(self.undo_button, 0, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(filter_dialog)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 0, 1, 1, 1)
        self.add_button = QtWidgets.QPushButton(filter_dialog)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.authors_table = QtWidgets.QTableWidget(filter_dialog)
        self.authors_table.setObjectName("authors_table")
        self.authors_table.setColumnCount(2)
        self.authors_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.authors_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.authors_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.authors_table)

        self.retranslateUi(filter_dialog)
        QtCore.QMetaObject.connectSlotsByName(filter_dialog)

    def retranslateUi(self, filter_dialog):
        _translate = QtCore.QCoreApplication.translate
        filter_dialog.setWindowTitle(_translate("filter_dialog", "Dialog"))
        self.undo_button.setText(_translate("filter_dialog", "Undo"))
        self.save_button.setText(_translate("filter_dialog", "Save"))
        self.add_button.setText(_translate("filter_dialog", "+"))
        item = self.authors_table.horizontalHeaderItem(0)
        item.setText(_translate("filter_dialog", "Author"))
        item = self.authors_table.horizontalHeaderItem(1)
        item.setText(_translate("filter_dialog", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    filter_dialog = QtWidgets.QDialog()
    ui = Ui_filter_dialog()
    ui.setupUi(filter_dialog)
    filter_dialog.show()
    sys.exit(app.exec_())
