# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/templates/info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(668, 635)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.title = QtWidgets.QLabel(Form)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.wsdfs = QtWidgets.QLabel(Form)
        self.wsdfs.setObjectName("wsdfs")
        self.verticalLayout.addWidget(self.wsdfs)
        self.author = QtWidgets.QLabel(Form)
        self.author.setObjectName("author")
        self.verticalLayout.addWidget(self.author)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.description = QtWidgets.QLabel(Form)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.search = QtWidgets.QPushButton(Form)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Title:"))
        self.title.setText(_translate("Form", "TextLabel"))
        self.wsdfs.setText(_translate("Form", "Author:"))
        self.author.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "Description:"))
        self.description.setText(_translate("Form", "TextLabel"))
        self.search.setText(_translate("Form", "Search for this book"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
